# Generated by Django 3.0.5 on 2020-06-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('person', '0021_auto_20200621_1700'), ('person', '0022_auto_20200621_2019'), ('person', '0023_speakerprofile_twitter'), ('person', '0024_auto_20200621_2112'), ('person', '0025_auto_20200621_2118'), ('person', '0026_auto_20200621_2121')]

    dependencies = [
        ('person', '0020_auto_20180922_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mastadon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personalWebsite',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='radioCallsign',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
