# Generated by Django 3.0.5 on 2020-06-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0042_question_is_visible_to_reviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
