# Generated by Django 3.0.5 on 2020-06-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0043_auto_20200607_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='editedVideo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
