# Generated by Django 3.0.5 on 2020-06-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0045_auto_20200607_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(default='submitted', max_length=26),
        ),
    ]
