# Generated by Django 3.0.5 on 2020-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0046_auto_20200614_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(default='submitted', max_length=9),
        ),
    ]
