# Generated by Django 3.0.5 on 2020-07-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0047_auto_20200614_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='currentCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
