# Generated by Django 3.0.5 on 2020-07-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0049_auto_20200722_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attendees',
            field=models.TextField(blank=True, null=True),
        ),
    ]
