# Generated by Django 3.0.5 on 2020-07-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_auto_20200719_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lastExport',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
